### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by JayaprakashReddy** [JayaprakashReddy/SEBC#2]

**Comment by JayaprakashReddy** [comment]
Starting with the lab

**Comment by JayaprakashReddy** [comment]
0_nodeIPs.md  file updated with nodes public DNS and IPs

**Comment by JayaprakashReddy** [comment]
For some reason the nodes are not reachable  often and the network seems to be bad.

**Comment by JayaprakashReddy** [comment]
Could resolve it with modifying security groups setting

**Comment by JayaprakashReddy** [comment]
installation/1_preinstall.md  updated with most of the answers

**Comment by JayaprakashReddy** [comment]
Seeing this issue as mysql replica is trying to connect to master
ERROR 1045 (28000): Access denied for user 'root@ec2-54-179-182-13.ap-southeast-1.compute.am'@'localhost' (using password: YES)

**Comment by mfernest** [comment]
This seems like an odd authentication string to use. @jamestyj could you walk through this with JP in the morning?

**Comment by jamestyj** [comment]
Sure

**Comment by JayaprakashReddy** [comment]
That authentication issue got fixed as I stopped iptables service .

**Comment by JayaprakashReddy** [comment]
Finished CM/CDH installation. 
One thing I found is that, though repo is configured to be 5.8.2 and the  CM installed is of the same version(5.8.2), CDH got installed for the version 5.8.3. 
![cdh installation_screen1](https://cloud.githubusercontent.com/assets/5959266/20890468/f819a5cc-bb41-11e6-9d2b-a69e8aea2914.png)

**Comment by JayaprakashReddy** [comment]
Uploaded the 3_cm_installed.png to repo

**Comment by jamestyj** [comment]
> One thing I found is that, though repo is configured to be 5.8.2 and the CM installed is of the same version(5.8.2), CDH got installed for the version 5.8.3.

That's expected. I'll explain tomorrow.

**Comment by JayaprakashReddy** [comment]
Create a local parcel repo manually dowloading the parcel file and manifest.json files ( for CDH ,Accumulo and Kafka ) and deploying them to local http server.
Local Repo looks as below.
![cdh local repo](https://cloud.githubusercontent.com/assets/5959266/20892145/e1325704-bb47-11e6-9acb-6542146f735a.png)

**Comment by JayaprakashReddy** [comment]
Updated the github repo with 4_local_repo.png

**Comment by mfernest** [comment]
`1_preinstall.md` - Did you try listing the contents for `/sys/kernel/mm` and working further from there?
`2_replica_working.md` - good
`3_cm_installed.png` - good
`4_local_repo.png` - 🏆 

Good work!
