### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by JayaprakashReddy** [JayaprakashReddy/SEBC#3]

**Comment by JayaprakashReddy** [comment]
As I shutdown the cluster instances over night, could not restore the cluster in the morning. After trying to fix it for sometime felt the need to recreate it afresh.  So at the moment trying to recreate it afresh

**Comment by JayaprakashReddy** [comment]
Just recreated the cluster

**Comment by JayaprakashReddy** [comment]
Update the lab : 1_terasort_tests.md

**Comment by JayaprakashReddy** [comment]
Snapshots lab completed :  2_snapshot_list.png,  2_snapshot_test.md  updated

**Comment by JayaprakashReddy** [comment]
HDFS HA lab completed : uploaded 3_HDFS_HA.png

**Comment by JayaprakashReddy** [comment]
CM User role change lab completed : Uploaded 4_CM_users.png

**Comment by JayaprakashReddy** [comment]
Replicate to another cluster  lab ( first lab) could not complete as I lost time initially and had to move on to next lab

**Comment by mfernest** [comment]
Marked INC for missing some lab steps and proper reporting.
