### ISSUE TITLE
YARN/RM Lab

### ISSUE THREAD

**Issue by JayaprakashReddy** [JayaprakashReddy/SEBC#4]

**Comment by JayaprakashReddy** [comment]
Just completed Static Service Pools checking lab : uploaded 2_service_usage.png

**Comment by JayaprakashReddy** [comment]
Doing the Math lab completed : 0_YARNCalcs.md and  1_YARNCalcs.png uploaded to repo

**Comment by JayaprakashReddy** [comment]
Tuning for YARN lab : Updated the script with corrections and changes : uploaded 3_YARNtest.sh.md

**Comment by JayaprakashReddy** [comment]
Tuning for YARN lab : could run a  few times changing the parameters. Could not quite get to max out the resource usage .
Uploading the  4_YARN_results.md , 5_YARN_Charts.png and submitting the lab

**Comment by mfernest** [comment]
Complete.
