### ISSUE TITLE
Security Lab

### ISSUE THREAD

**Issue by JayaprakashReddy** [JayaprakashReddy/SEBC#6]

**Comment by JayaprakashReddy** [comment]
Kerberos security enabled and all the following configuration files are uploaded.
kinit.md
krb5.conf.md
kdc.conf.md
kadm5.acl.md

**Comment by JayaprakashReddy** [comment]
Submitting Sentry lab :  uploaded sentry-test.md

**Comment by mfernest** [comment]
Quite thorough. Well done.
