### ISSUE TITLE
clients

### ISSUE THREAD

**Issue by JayaprakashReddy** [JayaprakashReddy/SEBC#7]

**Comment by JayaprakashReddy** [comment]
Hue user are synced with Linux users

[hive_status.txt](https://github.com/JayaprakashReddy/SEBC/files/638667/hive_status.txt)

**Comment by JayaprakashReddy** [comment]
Hue user are synced with Linux users
![hue_linux user are synced finally](https://cloud.githubusercontent.com/assets/5959266/21001065/392ae828-bd59-11e6-9f06-125cea0bc5d3.png)

**Comment by JayaprakashReddy** [comment]
Uploaded the hue user login screenshot :0_unix_login.png ( user george ). Strange the username is not showing up there.

**Comment by JayaprakashReddy** [comment]
hue is integrated with sentry. 
User  ferdinand should see sample_07  : screenshot here
![1_hue_sentry](https://cloud.githubusercontent.com/assets/5959266/21003666/97406862-bd67-11e6-80fd-5bba22744c13.png)

**Comment by JayaprakashReddy** [comment]
user george should be able to see all tables  ( screenshot below )
![2_hue_sentry](https://cloud.githubusercontent.com/assets/5959266/21003718/dee370ce-bd67-11e6-966e-c7fef298be53.png)

**Comment by JayaprakashReddy** [comment]
Hue load balancing is done . 1_hue_lb.png , 2_hue_lb.png for same user login
![2_hue_sentry](https://cloud.githubusercontent.com/assets/5959266/21003765/122f3814-bd68-11e6-9d36-db5ae40fbf10.png)
![1_hue_lb](https://cloud.githubusercontent.com/assets/5959266/21003764/122f24a0-bd68-11e6-8551-92ab5f1b1d52.png)

 screen shots are shared

**Comment by JayaprakashReddy** [comment]
Hue lab is done.

**Comment by mfernest** [comment]
Also well done -- good work.
